const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('api', {
  getVersion:          ()      => ipcRenderer.invoke('get-version'),
  checkForUpdates:     ()      => ipcRenderer.invoke('check-for-updates'),
  installUpdate:       (d)     => ipcRenderer.invoke('install-update', d),
  onUpdateAvailable:   (cb)    => ipcRenderer.on('update-available',  (_, d) => cb(d)),
  onUpdateProgress:    (cb)    => ipcRenderer.on('update-progress',   (_, p) => cb(p)),
  onUpdateStatus:      (cb)    => ipcRenderer.on('update-status',     (_, d) => cb(d)),
  listProfiles:        ()      => ipcRenderer.invoke('list-profiles'),
  saveProfile:         (p)     => ipcRenderer.invoke('save-profile', p),
  getProfile:          (id)    => ipcRenderer.invoke('get-profile', id),
  deleteProfile:       (id)    => ipcRenderer.invoke('delete-profile', id),
  getConfig:           ()      => ipcRenderer.invoke('get-config'),
  setConfig:           (obj)   => ipcRenderer.invoke('set-config', obj),
  checkChromium:       ()      => ipcRenderer.invoke('check-chromium'),
  installChromium:     ()      => ipcRenderer.invoke('install-chromium'),
  onChromiumProgress:  (cb)    => ipcRenderer.on('chromium-progress', (_, d) => cb(d)),
  openSpreadsheet:     ()      => ipcRenderer.invoke('open-spreadsheet'),
  saveFlow:            (d)     => ipcRenderer.invoke('save-flow', d),
  loadFlow:            ()      => ipcRenderer.invoke('load-flow'),
  // v1.2.8: list saved once-flows for setup/teardown dropdowns, and validate that a
  // flow's setup/teardown references resolve to existing once-flows.
  listOnceFlows:       ()      => ipcRenderer.invoke('list-once-flows'),
  validateFlowRefs:    (d)     => ipcRenderer.invoke('validate-flow-references', d),
  openFlowsFolder:     ()      => ipcRenderer.invoke('open-flows-folder'),
  openLogsFolder:      ()      => ipcRenderer.invoke('open-log-folder'),
  openFile:            (p)     => ipcRenderer.invoke('open-file', p),
  openExternal:        (url)   => ipcRenderer.invoke('open-external', url),
  startAutomation:     (d)     => ipcRenderer.invoke('start-automation', d),
  stopAutomation:      (d)     => ipcRenderer.invoke('stop-automation', d),
  getCheckpoint:       (id)    => ipcRenderer.invoke('get-checkpoint', id),
  findOrphanCheckpoints:()     => ipcRenderer.invoke('find-orphan-checkpoints'),
  loadCheckpoint:      (p)     => ipcRenderer.invoke('load-checkpoint', p),
  discardCheckpoint:   (p)     => ipcRenderer.invoke('discard-checkpoint', p),
  onAutomationEvent:   (cb)    => ipcRenderer.on('automation-event', (_, d) => cb(d)),
  runControl:          (d)     => ipcRenderer.invoke('run-control', d),
  // v1.3.4 Phase 3: worker-pool sizing + license-aware cap.
  getWorkerCaps:       ()      => ipcRenderer.invoke('get-worker-caps'),
  checkLicenseCap:     (d)     => ipcRenderer.invoke('check-license-cap', d),
});
